### ISSUE TITLE
fap won't run on Stable FW 0.74.2

### ISSUE THREAD

**Issue by I-Sketchii-I** [pbek/usb_hid_autofire#1]
At line ~28, `itoa` is used to convert `autofire_delay` values to `str` type and store it in the `autofire_delay_str` buffer
it looks like this is used to show the autofire delay in the GUI screen

when trying to compile with flipper zero FW:
```
fbt: warning: build\f7-firmware-D\.extapps\usb_hid_autofire.fap: app won't run. Unresolved symbols: {'itoa'} (in API, but disabled: {'itoa'})
validate_app_imports, line 204, in file "D:\Flipper Zero Stuff\flipperzero-firmware\scripts\fbt_tools\fbt_extapps.py"
```

`itoa` appears to be disabled in the official flipper zero FW API. The app compiles and runs if you comment out line 28:
`//itoa(autofire_delay, autofire_delay_str, 10);
`

I am not skilled in programming but I commented out lines 27 & 28 and just replaced `autofire_delay_str` in line 41 with `"10"` as a dumb but simple solution
Sorry if this should've been a PR or something, I just wanted to document what I did to get the .fap working on my flipper

**Comment by pbek** [comment]
Thank you for mentioning! It really doesn't seem to build any more. I just tested it in https://github.com/pbek/usb_hid_autofire/actions/runs/3850371823/jobs/6560439751. They seem to have removed it. I'll take a look at it.

**Comment by pbek** [comment]
Can you try again please?

**Comment by I-Sketchii-I** [comment]
I just tried compiling again with the new changes and it works! Thank you! :)

**Comment by pbek** [comment]
Great! 😁
