### ISSUE TITLE
The app no longer works with 0.91.4 firmware 

### ISSUE THREAD

**Issue by guglez** [pbek/usb_hid_autofire#4]
Hi,

the app no longer works. It’s showing the following error message:
Error
Preload failed

update application to use with this firmware (ApiToOld)

**Comment by pbek** [comment]
Hm, sre you using the pre-built binary. I guess it's best to build it yourself, the api is changing all the time

**Comment by pbek** [comment]
I, for example use these builds: https://github.com/xMasterX/all-the-plugins/releases/tag/12sep2023

**Comment by guglez** [comment]
I recompiled the app and it works! Thank you.

**Comment by pbek** [comment]
Great that worked!
